//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExigoIntegration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderID { get; set; }
        public int OrderNumber { get; set; }
        public string OrderNumberPrefix { get; set; }
        public string OrderNumberPostfix { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Notes { get; set; }
        public string ShippingFullName { get; set; }
        public string ShippingCompany { get; set; }
        public string ShippingStreet1 { get; set; }
        public string ShippingStreet2 { get; set; }
        public string ShippingStreet3 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingPhone { get; set; }
        public string ShippingEmail { get; set; }
        public string BillingFullName { get; set; }
        public string BillingCompany { get; set; }
        public string BillingStreet1 { get; set; }
        public string BillingStreet2 { get; set; }
        public string BillingStreet3 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPhone { get; set; }
        public string BillingEmail { get; set; }
        public string PaymentMethod { get; set; }
        public string CreditCardType { get; set; }
        public string CreditCardOwner { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardExpires { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public bool IsOrderSent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Tracking { get; set; }
        public string Carrier { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<bool> Voided { get; set; }
        public Nullable<System.DateTime> VoidedDate { get; set; }
        public string VoidedUser { get; set; }
        public string ServiceUsed { get; set; }
        public Nullable<decimal> TotalCharges { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<bool> ReturnShipment { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
